from enum import Enum


class ErrorCode(str, Enum):
    UNKNOWN = "UNKNOWN-ERROR"
    INVALIDDATA = "INVALID-DATA"
    STORAGEERROR = "STORAGE-ERROR"
    S3READERROR = "S3-READ-ERROR"
    S3WRITEERROR = "S3-WRITE-ERROR"
    S3DELETEERROR = "S3-DELTE-ERROR"
    CLIENTERROR = "CLIENT-ERROR"
    EMAILCLIENTERROR = "EMAIL-CLIENT-ERROR"
    SQSCLIENTERROR = "SQS-CLIENT-ERROR"
    ARGERROR = "ARGUMENT-ERROR"
    PARSERERROR = "PARSING-ERROR"
    MISSINGDATA = "MISSING-DATA"

